### ISSUE TITLE
query_msg_for__empty.json: Weird file name and value in title

### ISSUE THREAD

**Issue by taitruong** [CosmWasm/cw-nfts#130]
This problem doesn't exist in v0.17.0 anymore, since there is now only one schema file for cw721-base. Though it is worth checking why `cargo schema` creates this file, with title `QueryMsg_for_Empty` in line 3: [query_msg_for__empty](https://github.com/CosmWasm/cw-nfts/blob/v0.16.0/contracts/cw721-base/schema/query_msg_for__empty.json#L3):

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "QueryMsg_for_Empty",
  "oneOf": [
    {
      "description": "Return the owner of the given token, error if token does not exist Return type: OwnerOfResponse",
...
```

This causes ts-codegen not being able to create `ReadOnlyClientInterface` (since it doesn't find `QueryMsg`). Check issue here: https://github.com/CosmWasm/ts-codegen/issues/120

**Comment by JakeHartnell** [comment]
The reason it creates this file is that `QueryMsg` implements generics, i.e. `QueryMsg<QueryExtension>`, in `cw721-base` there is no query extension so the value is `QueryMsg<Empty>` which leads to `query_msg_for__empty.json`. Make sense?
