### ISSUE TITLE
Unable to upload cw721_base.wasm on terra-station

### ISSUE THREAD

**Issue by 0xWWW** [CosmWasm/cw-nfts#56]
Getting error with `cw721_base wasm` file on `artifacts` folder like the following screenshot .
![image](https://user-images.githubusercontent.com/50073310/156762000-b378c230-1b95-4fdf-85c0-51a1006bf3dd.png)

**Comment by JakeHartnell** [comment]
You'll need to use an older version. Terra does not support the latest version of CosmWasm. :smiling_face_with_tear: 

Believe this is the last supported release: https://github.com/CosmWasm/cw-nfts/releases/tag/v0.9.2
